name = "Relevant"
version = "0.1.0"
defaultTargets = ["relevant"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Relevant"

[[lean_exe]]
name = "relevant"
root = "Main"
